export const texts = {
  home: 'Home',
  search: 'Search',
  explore: 'Explore',
  reels: 'Reels',
  messages: 'Messages',
  notifications: 'Notifications',
  create: 'Create',
  profile: 'Profile',
  more: 'More',
  recent: 'Recent',
  clearAll: 'Clear All',
  createNewPost: 'Create new post',
  dragPhotosAndVideosHere: 'Drag photos and videos here',
  selectFromComputer: 'Select From Computer',
  thisWeek: 'This week',
  earlier: 'Earlier',
  thisMonth: 'This month',
  startedFollowingYou: 'started following you.',
  following: 'Following',
  mentionedYouInAComment: 'mentioned you in a comment:',
};
